source 'https://rubygems.org'

gem 'rails', '4.1.1'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'unicorn'
gem 'pg'
gem 'rack-handlers'
gem 'haml-rails'
gem 'rails-backbone'

gem 'haml_coffee_assets', git: 'https://github.com/netzpirat/haml_coffee_assets'
gem 'execjs'
gem 'jasmine-rails'
gem 'pjax_rails'
gem 'braintree-rails'
gem 'dotenv-rails'

gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem 'omniauth-twitter'
gem 'omniauth-yahoo'
gem 'mailboxer'
gem 'switch_user'
gem 'devise'
gem 'embedly'
gem 'redis-rails'
gem 'resque'
gem 'resque-scheduler', '~> 3.0.0', :require => 'resque-scheduler'
gem 'nokogiri'

gem 'sunspot_rails'
gem 'sunspot_solr'

group :development do
  #gem 'spring'
  gem 'capistrano'
  gem 'rvm-capistrano'
end
